build:
    wasm-pack build

run:
    npm install --save-dev \
        @wasm-tool/wasm-pack-plugin@latest \
        html-webpack-plugin@latest \
        webpack@latest \
        webpack-cli@latest \
        webpack-dev-server@latest
    npm run serve
