setup:
    npm install --save-dev \
        @wasm-tool/wasm-pack-plugin@latest \
        html-webpack-plugin@latest \
        webpack@latest \
        webpack-cli@latest \
        webpack-dev-server@latest

build:
    npm run build

test:
    cargo test
    set -eu; for runner in firefox chrome node; do \
        if [ "${runner}" = node ]; then \
            wasm-pack test "--${runner}"; \
        else \
            wasm-pack test "--${runner}" --headless; \
        fi; \
    done

run:
    npm run serve

clean:
    rm -fr node_modules/ pkg/
